---
apiVersion: v1
kind: Service
metadata:
  name: bpm-kafka-hq
spec:
  type: NodePort
  selector:
    app: bpm-kafka-hq
  ports:
    - port: 9999
      targetPort: 9999
      nodePort: 30999
      name: kafka-hq
---
---
apiVersion: v1
kind: Pod
metadata:
  name: bpm-kafka-hq
  labels:
    app: bpm-kafka-hq
spec:
  volumes:
    - name: kafka-hq-configuration
      configMap:
        name: kafka-hq-configuration
        defaultMode: 0777
  containers:
    - name: kafkahq
      image: tchiotludo/kafkahq
      volumeMounts:
        - mountPath: /app/application.yml
          subPath: application.yml
          name: kafka-hq-configuration