---
apiVersion: v1
kind: Service
metadata:
  name: bpm-kafka-schema-registry
spec:
  type: NodePort
  selector:
    app: bpm-kafka-schema-registry
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      name: schema-registry

---
apiVersion: v1
kind: Pod
metadata:
  name: bpm-kafka-schema-registry
  labels:
    app: bpm-kafka-schema-registry
spec:
  containers:
    - name: kafka-schema-registry
      image: confluentinc/cp-schema-registry:5.5.0
      env:
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: PLAINTEXT://bpm-kafka:9092
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: kafka-schema-registry
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://localhost:8081,http://bpm-kafka-schema-registry:8081
