---
apiVersion: v1
kind: Service
metadata:
  name: bpm-mongo
spec:
  type: NodePort
  selector:
    app: bpm-mongo
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30717
      name: mongo

---

apiVersion: v1
kind: Pod
metadata:
  name: bpm-mongo
  labels:
    app: bpm-mongo
spec:
  volumes:
    - name: create-mongo-users
      configMap:
        name: create-mongo-users-script
        defaultMode: 0777
  containers:
    - name: mongo
      image: mongo:4.2-bionic
      env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
      readinessProbe:
        exec:
          command:
            - /bin/bash
            - -c
            - /scripts/create-users.sh | cat
        initialDelaySeconds: 15
        periodSeconds: 120
      volumeMounts:
        - mountPath: /scripts
          name: create-mongo-users
